# Generated by Django 3.2.8 on 2021-10-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story',
            new_name='StoryModel',
        ),
    ]
