# Generated by Django 3.2.8 on 2021-10-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulate', '0002_rename_story_storymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
