# Generated by Django 3.2.8 on 2021-11-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulate', '0006_genremodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genremodel',
            name='story',
            field=models.ManyToManyField(blank=True, null=True, to='Articulate.StoryModel'),
        ),
    ]
