# Generated by Django 3.2.8 on 2021-11-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulate', '0007_alter_genremodel_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genremodel',
            name='story',
            field=models.ManyToManyField(to='Articulate.StoryModel'),
        ),
    ]
