# Generated by Django 3.2.8 on 2021-11-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulate', '0011_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='image',
        ),
    ]
