# Generated by Django 3.2.8 on 2021-11-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulate', '0012_rename_profile_image_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
